backend:
  name: github
  repo: uksurd88/codewaffle
  branch: main
  base_url: https://sveltia-cms-auth.sukhdeepsingh.workers.dev  # optional: use if you want OAuth via Cloudflare Worker (free)

media_folder: "public/images/posts"
public_folder: "/images/posts"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", default: ["science"] }
      - label: "Authors"
        name: "authors"
        widget: "list"
        default: ["Sukhdeep Singh"]
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
